[autopilot]
enabled = true

[traffic_manager]
auto_lane_change = false
distance_to_leading_vehicle = 5.0

ignore_lights_percentage = 0
ignore_signs_percentage = 0
ignore_vehicles_percentage = 0
ignore_walkers_percentage = 0

keep_right_rule_percentage = 0
random_left_lanechange_percentage = 0
random_right_lanechange_percentage = 0

update_vehicle_lights = true
vehicle_lane_offset = 0.0
vehicle_percentage_speed_difference = 0.0

;true: right, false: left
force_lane_change_enabled = false
force_lane_change_direction = true

[reload]
interval_sec = 1.0
