; ----------------------------------------
; - SENSORS CONFIGURATION
; ----------------------------------------

; ----------------------------------------
; - RGB Camera
[RGBCamera]
enabled = true
display_pos = 0,0
x=0.8
y=0.0
z=1.5
roll=0
pitch=0
yaw=0
image_size_x = 1920
image_size_y = 1080
fov = 90
; ----------------------------------------

; ----------------------------------------
; - Depth Camera
[DepthCamera]
enabled = false
display_pos = 0,0
x=0.8
y=0.0
z=1.5
roll=0
pitch=0
yaw=0
image_size_x = 1920
image_size_y = 1080
fov = 90
color_converter = LogarithmicDepth
; ----------------------------------------

; ----------------------------------------
; - Semantic Segmentation Camera
[SemanticSegCamera]
enabled = false
display_pos = 0,0
x=0.8
y=0.0
z=1.5
roll=0
pitch=0
yaw=0
image_size_x = 1920
image_size_y = 1080
fov = 90
color_converter = CityScapesPalette
; ----------------------------------------

; ----------------------------------------
; - LiDAR
[LiDAR]
enabled = false
display_pos = 0,0
x=0.0
y=0.0
z=2.4
channels = 64
range = 100
points_per_second = 250000
rotation_frequency = 20
upper_fov = 10
lower_fov = -30
noise_stddev = 0.0
sensor_tick = 0.1
; ----------------------------------------

; ----------------------------------------
; - Radar
[Radar]
enabled = false
display_pos = 0,0
x=1.5
y=0.0
z=0.5
horizontal_fov = 80
vertical_fov = 20
range = 80
points_per_second = 1500
sensor_tick = 0.05
; ----------------------------------------

; ----------------------------------------
; - GNSS
[GNSS]
enabled = false
x=0.0
y=0.0
z=2.2
sensor_tick = 0.2
; ----------------------------------------

; ----------------------------------------
; - IMU
[IMU]
enabled = false
x=0.0
y=0.0
z=2.2
sensor_tick = 0.05
; ----------------------------------------

; ----------------------------------------
; - Collision Sensor
[Collision]
enabled = false
x=0.0
y=0.0
z=0.0
; ----------------------------------------

; ----------------------------------------
; - Lane Invasion Sensor
[LaneInvasion]
enabled = false
x=0.0
y=0.0
z=0.0
; ----------------------------------------

; ----------------------------------------
; - Obstacle Sensor
[Obstacle]
enabled = false
x=0.0
y=0.0
z=0.0
distance = 20
hit_radius = 0.5
only_dynamics = true
; ----------------------------------------


; ----------------------------------------
; - DISPLAY CONFIGURATION
; ----------------------------------------
[sensor_system]
reload_interval_sec = 1.0
terminal_print_interval_sec = 0.5

[display]
rows = 0
cols = 0

[spectator]
chase_back = 8.0
chase_up = 3.0
chase_pitch = -10.0

top_z = 60.0
top_pitch = -89.0
top_yaw = 0.0

fp_front = 1.8
fp_up = 1.35
fp_pitch = -2.0

map_view_z = 220.0
map_view_pitch = -89.0
map_view_yaw = -90.0

[visualization]
; LiDAR point color mode:
;   NORMAL     -> white points on BLACK background
;   DISTANCE   -> colormap by distance (BLACK background fixed)
;   INTENSITY  -> colormap by intensity (BLACK background fixed)
lidar_point_mode = DISTANCE
; NEW: LiDAR colormap option
;   RAINBOW  : red -> ... -> purple-ish
;   RED_BLUE : red -> ... -> blue
lidar_colormap = RED_BLUE
; DISTANCE Mode Settings:
lidar_dist_min = 0.0
lidar_dist_max = 100.0
; INTENSITY Mode Settings:
lidar_intensity_min = 0.0
lidar_intensity_max = 1.0
lidar_gamma = 1.0
lidar_zoom = 2.0
lidar_point_radius = 1.0

; Radar point color mode:
;   NORMAL   -> white points
;   DEPTH    -> grayscale by depth
;   VELOCITY -> red(approaching)/blue(receding), near 0 -> white
radar_point_mode = VELOCITY
; DEPTH Mode Settings:
radar_depth_min = 0.0
radar_depth_max = 80.0
; VELOCITY Mode Settings:
radar_vel_min = -10.0
radar_vel_max = 10.0
radar_point_radius = 4.0
;2.0

; ----------------------------------------
; - CONTROL CONFIGURATION
; ----------------------------------------
[manual_vehicle]
throttle = 0.70
brake = 1.00
steer_step = 0.03
steer_return = 0.80